### ISSUE TITLE
Readme link doesn't exist

### ISSUE THREAD

**Issue by kounkou** [chezou/mecab-conda-recipe#1]
Hi @chezou 

Could you provide the tutorial please,
Indeed, the given page doesn't exist :
https://conda.io/en/latest/build_tutorials/postgis.html

Regards

**Comment by chezou** [comment]
Thanks for letting me know.

Unfortunately, I don't have any motivation to maintain this repository since anaconda document structure had been changed significantly. Will archive the repo.
